#prefix used to show metrics in AppDynamics
metricPrefix: "Server|Component:<TIER_ID>|Custom Metrics|Azure|"
#metricPrefix: "Custom Metrics|Azure|"

accounts:
  - displayName: "Azure VM"
    credentials:
         subscriptionId: ""
         client: ""
         tenant: ""
         secret: ""

    services:
       - resourceGroups: ["my-rg"]  # Please put the required resourceGroups only
         serviceName: "Virtual machine"
         regions: ["East US 2"]
         serviceInstances: ["vm.*"]


proxyConfig:
  host:
  port:
  username:
  password:

metricsTimeRange:
  startTimeInMinsBeforeNow: 10
  endTimeInMinsBeforeNow: 0

concurrencyConfig:
  noOfResourceGroupThreads: 3
  noOfServiceCollectorThreads: 3
  threadTimeout: 30  #Thread timeout in seconds

connection:
  sslCertCheckEnabled: false
  socketTimeout: 10000
  connectTimeout: 10000

#By default we support upto 5 accounts, and 1 thread is required per account.
numberOfThreads: 5
#filterStats: false
#================================= Example configurations below =================================
#  - displayName: "AzureAccount Storage"
#    resourceGroups: ["test-ext.*"]
#    serviceName: "Storage account"
#    regions: ["East US"]
#    serviceInstances: [".*"]

#  - displayName: "AzureAccount Sql server"
#    resourceGroups: [".*"]
#    serviceName: "SQL server"
#    regions: ["australia.*"]
#    serviceInstances: [".*"]

controllerInfo:
  controllerHost: ""
  controllerPort: 8080
  account: "customer1"
  username: "user1"
  password: "welcome"
  encryptedPassword: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: ""
  accountAccessKey: ""
  machinePath: ""
  simEnabled: true
  applicationName: ""
  tierName: ""
  nodeName: ""

#Encryption key for your controllerInfo password
encryptionKey: ""
